### ISSUE TITLE
Add support for OpenH264

### ISSUE THREAD

**Issue by alexbbb** [alexbbb/pjsip-android-builder#2]
Enhance the compilation process by adding <b>OpenH264</b> for every target arch.
Follow the instructions here: http://trac.pjsip.org/repos/ticket/1758 and then make sure to copy the generated .so files in the final build folder for every arch. Also check if the latest OpenH264 release works. Actually, version 1.4.0 is out, but the ticket on PJSIP trac suggests to use 1.0.0.

**Comment by alexbbb** [comment]
Support for archs armeabi, armeabi-v7a and x86 is complete.
Compilation errors occurs for x86_64 and arm64-v8a

**Comment by alexbbb** [comment]
Support for x86_64 and arm64-v8a will be added in a future release

**Comment by gotev** [comment]
OpenH264 1.0.0 does not support 64 bit architectures, as can be seen from here: https://github.com/cisco/openh264/releases. Newer releases have added that support, but they are not compatible with pjsip 2.4.5 out of the box.
