### ISSUE TITLE
Openssl x86_64 build error 

### ISSUE THREAD

**Issue by zokipirlo** [alexbbb/pjsip-android-builder#4]
Hi!

I couldn't build openssl for x86_64 target. I had an error like that
````
cryptlib.c:1:0: error: CPU you selected does not support x86-64 instruction set
````
I found out that this is the only target that didn't have ARCH_FLAGS and ARCH_LINK defined. So I added inside this target
````
export ARCH_FLAGS=
export ARCH_LINK=
```
and after that build succeeded. Is this a correct solution?

Thanks for this project. I owe you a beer :smile: Cheers :beer:

**Comment by alexbbb** [comment]
Glad that the script's been useful to you :) 
If it compiles and the resulting library is working, then it's OK :+1: 

Just for my personal curiosity and to understand why the default script settings have not worked in your case...which Linux distribution and which virtualization system have you used? On my Ubuntu Server 14.04.3 LTS, OpenSSL compiles successfully even without those exports

**Comment by zokipirlo** [comment]
I'm building this on OSX 10.10. And I have modified script a little, so that both files (openssl-build-target-archs and openssl-build) are merged in one (openssl-build script is a function).
It wasn't meant to be a bug report, just asking a question what do you think :)
