### ISSUE TITLE
arm-linux-androideabi-ar: ../libcrypto.a: Malformed archive

### ISSUE THREAD

**Issue by sinosoidal** [alexbbb/pjsip-android-builder#5]
Hi,

I'm trying to use your script to compile openssl. During the linking phase it fails with "Malformed archive"

I have been googling around and I can't find an answer to this. Do you have a clue?

Regards,

Nuno

**Comment by alexbbb** [comment]
On which OS are you compiling?

**Comment by sinosoidal** [comment]
Mac OSX El Capitain

**Comment by alexbbb** [comment]
Please post the full `./openssl-build` command that you use to compile and some relevant output

**Comment by sinosoidal** [comment]
MACKIE:workspace nsantos$ ./openssl-build.sh ~/android/ndk ~/Downloads/openssl-master 15 armeabi-v7a 4.9 build 
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: /tmp/openssl/android-toolchain-arm
Cleaning up...
Done.
-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include
Configuring for android-armv7
    no-deprecated   [default]  OPENSSL_NO_DEPRECATED (skip dir)
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
    no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-shared       [default] 
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-store        [experimental] OPENSSL_NO_STORE (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-zlib         [default] 
    no-zlib-dynamic [default] 
IsMK1MF=0
CC            =/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc
CFLAG         =-DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot=$(CROSS_SYSROOT) -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
EX_LIBS       =-ldl
CPUID_OBJ     =armcap.o armv4cpuid.o
BN_ASM        =bn_asm.o armv4-mont.o armv4-gf2m.o
EC_ASM        =ecp_nistz256.o ecp_nistz256-armv4.o
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes_cbc.o aes-armv4.o bsaes-armv7.o aesv8-armx.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4_enc.o rc4_skey.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =
SHA1_OBJ_ASM  =sha1-armv4-large.o sha256-armv4.o sha512-armv4.o
RMD160_OBJ_ASM=
CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o
MODES_OBJ     =ghash-armv4.o ghashv8-armx.o
ENGINES_OBJ   =
PROCESSOR     =
RANLIB        =/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-ranlib
ARFLAGS       =
PERL          =/opt/local/bin/perl5
THIRTY_TWO_BIT mode
DES_UNROLL used
DES_INT used
BN_LLONG mode
RC4 uses uchar
RC4_CHUNK is unsigned long
BF_PTR used

Configured for android-armv7.
making all in crypto...
/opt/local/bin/perl5 ../util/mkbuildinf.pl "/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM" "android-armv7" >buildinf.h
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o cryptlib.o cryptlib.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o mem.o mem.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o mem_dbg.o mem_dbg.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o cversion.o cversion.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o ex_data.o ex_data.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o cpt_err.o cpt_err.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o ebcdic.o ebcdic.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o uid.o uid.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o o_time.o o_time.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o o_str.o o_str.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o o_dir.o o_dir.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o thr_id.o thr_id.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o lock.o lock.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o fips_ers.o fips_ers.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o o_init.o o_init.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o o_fips.o o_fips.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I. -I.. -I../include -Iinclude  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM  -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -I/Users/nsantos/android/ndk/platforms/android-9/arch-arm/usr/include  -c -o sec_mem.o sec_mem.c
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-ar  r ../libcrypto.a cryptlib.o mem.o mem_dbg.o cversion.o ex_data.o cpt_err.o ebcdic.o uid.o o_time.o o_str.o o_dir.o thr_id.o lock.o fips_ers.o o_init.o o_fips.o sec_mem.o armcap.o armv4cpuid.o
/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-ar: ../libcrypto.a: Malformed archive
make[1]: *** [../libcrypto.a] Error 1
make: *** [build_crypto] Error 1

**Comment by alexbbb** [comment]
Try setting GCC version to 4.8

**Comment by sinosoidal** [comment]
The same problem happens! :(

I have been googling around this all day and all the people complaining about similar problems say the solution is to make clean. The thing is that, using your scripts, a clean environment is always used.

**Comment by alexbbb** [comment]
This is the reason why I use virtual machines to make this kind of builds. To avoid headaches, I suggest you to follow my tutorial (see README) and get yourself an Ubuntu Server 14.04 VM. The initialization script handles all the downloads and the installation of the needed toolchains. It will take a while, depending on your bandwidth, but I'm sure that everything will work. Plus, you have the advantage of VM snapshots, that will guarantee you starting from a truly clean environment every time.

**Comment by sinosoidal** [comment]
Alex, just found something.

I have been messing with the command:

/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-ar  r ../libcrypto.a cryptlib.o mem.o mem_dbg.o cversion.o ex_data.o cpt_err.o ebcdic.o uid.o o_time.o o_str.o o_dir.o thr_id.o lock.o fips_ers.o o_init.o o_fips.o sec_mem.o armcap.o armv4cpuid.o

I have removed all the parameters and left only "r ../libcrypto.a" and it still complained 

So I decided to delete ../libcrypto.a which incredibly already exists (I though the purpose of ar command was to create such file).

After deleting it, I decided to run the whole command again:

/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-ar  r ../libcrypto.a cryptlib.o mem.o mem_dbg.o cversion.o ex_data.o cpt_err.o ebcdic.o uid.o o_time.o o_str.o o_dir.o thr_id.o lock.o fips_ers.o o_init.o o_fips.o sec_mem.o armcap.o armv4cpuid.o

And now it worked!

Questions: why is a libcrypto.a being created in first place?

Does this ring any bell to you?

Regards,

Nuno

**Comment by sinosoidal** [comment]
Forget it! :) 

I have found the problem. I was trying to build openssl before finding your scripts. Therefore, there was already a libcrypto.a inside the openssl source dir. 

For this reason, everytime I called the scripts, the file get copied, resulting in a error! It's already compiling.

By the way, your scripts don't seem to contemplate the android-x86 case. For any special reason?

Regards,

Nuno

**Comment by sinosoidal** [comment]
Now I'm with this problem:

/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc -I.. -I../crypto -I../include -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -I/Users/nsantos/android/ndk//platforms/android-9/arch-arm/usr/include   -c -o app_rand.o app_rand.c
rm -f openssl
shlib_target=; if [ -n "" ]; then \
		shlib_target="linux-shared"; \
	fi; \
	LIBRARIES="-L.. -lssl -L.. -lcrypto" ; \
	/Applications/Xcode.app/Contents/Developer/usr/bin/make -f ../Makefile.shared -e \
		APPNAME=openssl OBJECTS="openssl.o asn1pars.o ca.o ciphers.o cms.o crl.o crl2p7.o dgst.o dhparam.o dsa.o dsaparam.o ec.o ecparam.o enc.o engine.o errstr.o gendsa.o genpkey.o genrsa.o nseq.o ocsp.o passwd.o pkcs12.o pkcs7.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o prime.o rand.o req.o rsa.o rsautl.o s_client.o s_server.o s_time.o sess_id.o smime.o speed.o spkac.o srp.o ts.o verify.o version.o x509.o rehash.o apps.o opt.o s_cb.o s_socket.o app_rand.o" \
		LIBDEPS="-pie $LIBRARIES -ldl" \
		link_app.${shlib_target}
( :; LIBDEPS="${LIBDEPS:--pie -L.. -lssl -L.. -lcrypto -ldl}"; LDCMD="${LDCMD:-/tmp/openssl/android-toolchain-arm/bin/arm-linux-androideabi-gcc}"; LDFLAGS="${LDFLAGS:--DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -mandroid -fPIC --sysroot= -Wa,--noexecstack -Wall -O3 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -I/Users/nsantos/android/ndk//platforms/android-9/arch-arm/usr/include}"; LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`; LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`; LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=openssl} openssl.o asn1pars.o ca.o ciphers.o cms.o crl.o crl2p7.o dgst.o dhparam.o dsa.o dsaparam.o ec.o ecparam.o enc.o engine.o errstr.o gendsa.o genpkey.o genrsa.o nseq.o ocsp.o passwd.o pkcs12.o pkcs7.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o prime.o rand.o req.o rsa.o rsautl.o s_client.o s_server.o s_time.o sess_id.o smime.o speed.o spkac.o srp.o ts.o verify.o version.o x509.o rehash.o apps.o opt.o s_cb.o s_socket.o app_rand.o ${LIBDEPS} )
/private/tmp/openssl/android-toolchain-arm/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: fatal error: --sysroot=: must take a non-empty argument
collect2: error: ld returned 1 exit status
make[2]: *** [link_app.] Error 1
make[1]: *** [openssl] Error 2
make: *** [build_apps] Error 1

Does this ring any bell?

Thanks,

Nuno

**Comment by alexbbb** [comment]
> By the way, your scripts don't seem to contemplate the android-x86 case. For any special reason?

x86 target ABI for Android is already supported by the build script. https://github.com/alexbbb/pjsip-android-builder#build-only-openssl

Please, make use of [markdown syntax](https://guides.github.com/features/mastering-markdown/) to highlight code and console output in your comments, as the output is very hard to read :(

**Comment by sinosoidal** [comment]
Alex,

I decided to give a shot with the virtual machine. So far so good. 

Regards

**Comment by manjunath143** [comment]
I still see same error for x86 .Any idea ?
