### ISSUE TITLE
Building for 16 KB page sizes, an impossible task?

### ISSUE THREAD

**Issue by NLLAPPS** [alexbbb/pjsip-android-builder#57]
Hi, as per [https://developer.android.com/guide/practices/page-sizes ](https://developer.android.com/guide/practices/page-sizes ) Google will be forcing 16 KB page size from next year. 

My understanding is that changing pjsip-android-builder to produce binaries with 16 KB page size is not an easy task. How would one start about implementing this?

**Comment by xrelevena-tech** [comment]
This project hasn't been updated for several years. Does it support 16kb? Where can I find it?
