### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by JavaMachine** [alexbbb/pjsip-android-builder#6]
Hello,

I have built pjsip with "./build" and everything is ok... and implemented library into android...

But the problem is when I try to connect to my Kamailio Server using TLS...

java.lang.Exception: Title:       pjsua_call_make_call(acc.getId(), &pj_dst_uri, param.p_opt, this, param.p_msg_data, &id)
Code:        171060
W/System.err: Description: Unsupported transport (PJSIP_EUNSUPTRANSPORT)

My question is... if I built PJSIP with "./build" will it build with OpenSSL/TLS/SSL enabled? Or I missed something? Where and What I might did wrong ?

Thanks in advance...

**Comment by alexbbb** [comment]
The library is build with OpenSSL by default, so the transport should be supported. PJSIP uses autoconf to detect OpenSSL. if there are any error regarding this, you will see it in the build logs. Check also your server configuration.

**Comment by dragosgr** [comment]
Did you manage to connect using TLS?
