### ISSUE TITLE
Building TARGET_ANDROID_API=14

### ISSUE THREAD

**Issue by JavaMachine** [alexbbb/pjsip-android-builder#7]
I cloned this repository and edited config.conf before executing "./prepare-build-system".
And I edited following line:
#Target Android API level
TARGET_ANDROID_API=21

to

#Target Android API level
TARGET_ANDROID_API=14

When I want to build PJSIP I am getting error...

~/pjsip-android-builder# ./build
Clear final build folder ...
Creating config site file for Android ...
Compile PJSIP for arch armeabi ...
cp: cannot stat ‘/root/pjsip-android-builder/libyuv-android/libs/armeabi/libyuv.so’: No such file or directory

Where and What I did wrong? It seems script is not compiling these library (libyuv) at all...

Thanks in advance

**Comment by alexbbb** [comment]
When you set that parameter, you have to re-run the `./prepare-build-system` script again, as the additional libraries used in the PJSIP `./build` script are compiled by that script. I suggest you to also set the following parameters in the configuration to 0:
```
SETUP_PACKAGES=0
DOWNLOAD_NDK=0
DOWNLOAD_SDK=0
DOWNLOAD_PJSIP=0
```

**Comment by alexbbb** [comment]
Libyuv is compiled when you execute "./prepare-build-system" and if any error arises, you will see it directly in the console. All the additional libraries are built right after they're downloaded (because generally you need to build them only once to generate the needed .a and .so files), so I suggest you to adjust the configuration settings (refer to config.conf) to only download libyuv and then re-run the prepare-build-system script, so you could see what goes wrong. The "./build" script compiles only PJSIP and links it to the previously built libraries. The error you've seen is because libyuv compilation failed for some reason.

**Comment by JavaMachine** [comment]
Thank you for your reply... I have enabled Libyuv and OpenH264 in configuration files...
I am not sure if it is compiling for API 14 :(
BTW: libyuv successfully compiled... and how I can check if it is built for API 14? :)

Patching OpenH264 to be able to compile with Android API 21+..
patching file README.md
Hunk #1 succeeded at 69 (offset 2 lines).
patching file build/platform-android.mk
Hunk #1 FAILED at 12.
1 out of 1 hunk FAILED -- saving rejects to file build/platform-android.mk.rej
patching file codec/common/inc/crt_util_safe_x.h
patching file codec/common/inc/measure_time.h
patching file codec/common/src/crt_util_safe_x.cpp
patching file codec/decoder/plus/src/welsDecoderExt.cpp
Hunk #1 succeeded at 63 (offset -2 lines).
patching file codec/encoder/plus/src/welsEncoderExt.cpp
Building OpenH264 for target arch armeabi ...
Building OpenH264 for target arch armeabi-v7a ...
Building OpenH264 for target arch x86 ...
Building OpenH264 for target arch x86_64 ...

Thanks in advance....

**Comment by alexbbb** [comment]
The log you posted is all right. `1 out of 1 hunk FAILED` is perfectly normal. From what I see you build successfully OpenH264 for all the supported archs.
If you want to be sure that libyuv compiles from scratch, in `config.conf` set only `DOWNLOAD_LIBYUV=1` and then execute `./prepare-build-system`. After the compilation you will see all the binary files in `libyuv-android/jni`
